version: '3'
services:
    backend:
      build: ./backend
      container_name: sdte-backend
      ports:
        - 3050:3000
    frontend:
      build: ./frontend
      container_name: sdte-frontend
      ports:
      - 8086:80